language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew assembleDebug test check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: UiOM+Qr3ghDO6QyWmXcPpBmbuBe80OqLBM6+g7r+elbWjLgcsvaS4tsOuPJnvX+SSzgrUnMJLruzw0w7JXDGCtDsxR/ygN5+C/YkjVjEA0qyCDaTnJQVh9tYVwBy4zbaSaRFMVAxleBQwR1OjMetLMMTsOR8q7YpUt1I6AJzcQGUscobbEOks7TiWUNX21kDzjWbyV5sC/xPx52uAi4SVJJosExlnRz8THGBSTl7COMxE4yw5XksDw/BYDi8A8y21GP0tqgo8wdE3NTpfdMylhkOMwL5cYBAjxudAWn8XtfG54pRYjyFjdgQpKNcDM2JLUE7IjQ+DrC2DvjMKaATWHmohGOZZmb4gYCONoLZyR4UsnMObvKFpooc8401wHxPZ3Yk4vFNMJH1Nik/KsCnV0PITPVrEn135XVsjdwkR8Ntl7f2DVqOHfJrJhEtU+QnSQhAOK5+S/TAGPVlbRhDKpLxfnMZh61tqgfZFBqWFsDtmuq4B8A/FmffFzPstzMWv+/sp6xAXgVfK+UvSBGifm3RgayXpO4qDi7nt38w2lyhQVtgrXLtZVqBKGzvRJRIAQgoe8MJprbU2z90xKPj8smkOMkIGAsdbSEgyC3QrrJMWGKv1rFfpZT7AhyVRsZlb4FAEKEInE0MCRudMWRdI8S+X+rqbRXaQQvwCkd/DXA=
    - secure: Fo9GFxUsipCp5n4KuOK8ap6NTEV9Vt8a8dqUi+/ZgQQcFeNEUhg79h88DnVxTUZTVfB4VNWz5L2uOdhNIcBn3UCkW+I56obDc4VC85QJoZCOyagTQueLLExcklLdxyTMK2577d8P9bVsqLX7oNfnGI7y/6Z2Vh5u/kNfOOR6GkeFuP9ptX34TrCv0JDBrwuBgCPz+/daDiFFEpNDjGahWjSIZ8rs91gh4QGIWZk1tq3czP+3Biuj6Urk78RFO+UM9QlXk0Ayl6brodjGCjlRzjITzkKWaD7o+mw1EDRimkgTT0HwiiSEJJgQhxPwyIL4M4r7cKLUmx86FEgVtLY/tOcylNwYWEsotW4NIeiWZDG4kOFZQjoBhsvzGgS23r9aUQi03eYjDQ2SDTurH/DSe2IEm6BVaDDBOIA88FoU040TbiSf59OwSic1S+UlMRGUxmG/r69g+RVG6CZMUxTI2ypHtpAK3Sv2oR7GNcIOeAciwDCuNATBy60x13zyWnXI0mbmFBe7o0YqqwCO4ANxCX9agNdQ7E5IqdHZv7TF7DZfVo2skmyM4DI1oRN82icCDdw1QmdIfw2okq4D5c2Deuc0gRnZU/iXIUgKenkxcnjd0BeUUHe4eioR4ihCSHqwkIyI/zWYIaekRQ8Lz3w+ov2XKK1zCqeMcN+9OcroWkc=

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
